version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file:
      - .env
    restart: always
    depends_on:
        - db
    ports:
      - "8080:8080"
    command: >
      uvicorn api.app:app --host 0.0.0.0 --port 8080 --reload
   
   frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
