"""User repository module."""

import uuid

from db.models import User
from schemas.user import UserLogin, UserReg
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from utils.utils import hash_password


class UserRepository:
    """User repository class, which contains methods for user data manipulation."""

    def __init__(self, session: AsyncSession):
        """Initialize user repository with a database session."""
        self.session = session

    async def get_user_by_id(self, user_id: uuid.UUID.hex) -> User | None:
        """
        Get a user by user id,
        the id is generated by uuid and works as unique indetifier for user.

        Args:
            username (str): The id of the user.

        Returns:
            User | None: The user object if found, None otherwise
        """
        user = await self.session.scalars(select(User).where(User.user_id == user_id))
        return user.first()

    async def write_user(self, user: UserReg) -> User:
        """
        Write a user to the database.

        Args:
            user (UserReg): The user to write.

        Returns:
            User: The written user object.
        """
        hashed_password = await hash_password(user.password)
        user_obj = User(
            **user.model_dump(exclude={"password"}), password=hashed_password
        )
        self.session.add(user_obj)
        await self.session.commit()
        await self.session.refresh(user_obj)
        return user_obj
