FROM python:3.12

WORKDIR /history

COPY history/requirements.txt .

RUN pip install --upgrade setuptools
RUN pip install --no-cache-dir -r requirements.txt


COPY history/. .
COPY schemas/. ./schemas/.

EXPOSE 80

CMD [ "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80" ]
