FROM python:3.12

WORKDIR /history

COPY history/requirements.txt .
COPY history/requirements.adapter.txt .

RUN pip install --upgrade setuptools
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements.adapter.txt

COPY /history/. .
COPY /schemas/. ./schemas/.

VOLUME [ "/config" ]

CMD [ "python", "adapter.py" ]
